### ISSUE TITLE
Disabling .gitconfig disables much more than just proxy for me!

### ISSUE THREAD

**Issue by Sam-Martin** [markwragg/PowerShell-MacTools#1]
Consider using something like the methodology listed here: https://gist.github.com/manekinekko/2b4a29fe35c292b6f72f

**Comment by markwragg** [comment]
Good idea, thanks! It occurred to me also I could test if the proxy responds and then flip it automatically in my profile.ps1.

**Comment by markwragg** [comment]
Added Set-GitProxy that works as you suggested.
